# Generated by Django 2.0.2 on 2018-02-18 08:50

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='patient',
            managers=[
                ('Manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='position',
        ),
        migrations.AddField(
            model_name='patient',
            name='phoneNumber',
            field=models.TextField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
