# Generated by Django 2.0.2 on 2018-02-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0002_auto_20180218_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='index',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
